server:
  port: 8090
  tomcat:
    max-threads: 1
    min-spare-threads: 1
spring:
  redis:
    database: 0
    host: 10.241.117.38
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 4
        # 连接池中的最大空闲连接
        max-idle: 4
        # 连接池中的最小空闲连接
        min-idle: 1
        # 连接池最大阻塞等待时间
        max-wait: 1000